In [1]:
import pandas as pd

pd.set_option('display.max_colwidth', 100)
news = pd.read_csv(r"E:\Development\Python\ML\CRUV Python roject\news.csv")
news.head(6)

,title,content,published_at,source,topic
0,"BTS: RM is reminded of Bon Voyage as he travels in Switzerland, gives glimpse of Chris Martin's ...","After reaching his hotel in the city, RM revealed that his stay would be for four days and added...",2022-07-30T07:00:00Z,2,13
1,RM recalls wondering if he 'made right decision by joining' BTS: I was thinking about how I woul...,RM aka Kim Namjoon was the first member to join BTS. The group released their debut single album...,2022-12-22T15:57:55Z,2,13
2,BTS: J-Hope and RM go bonkers at Billie Eilish's concert; ARMY rejoice seeing Namjoon and Hobi's...,"Billie Eilish's concert was held in Seoul, South Korea and it was attended by BTS' RM aka Kim Na...",2022-08-16T07:00:00Z,1,7
3,"BTS: J-Hope proudly states he raised Jungkook, Jimin and Kim Taehyung; ARMY gets emotional [Watch]","BTS ARMY y'all would be missing the members a lot, right? Well, one of the BTS members Kim Seokj...",2022-12-18T13:08:40Z,1,7
4,BTS: Jin aka Kim Seokjin takes us through the Super Tuna journey; his unbridled excitement on ca...,BTS member Kim Seokjin aka Jin has the capacity to create diverse content. This has come through...,2022-11-21T08:00:00Z,1,8
5,"BTS: J-Hope aka Jung Hoseok sets thirst trap with his live after reaching Chicago; ARMY says, 'W...",BTS member J-Hope aka Jung Hoseok has reached Chicago. He is there for the final day of the Loll...,2022-07-25T07:00:00Z,1,7

In [2]:
news.shape

(810, 5)

In [3]:
col = news.columns
col

Index(['title', 'content', 'published_at', 'source', 'topic'], dtype='object')

In [4]:
for column in col:
    print(f"\n{column} : {news[column][0]}")

title : BTS: RM is reminded of Bon Voyage as he travels in Switzerland, gives glimpse of Chris Martin's chair to fans. Watch

content : After reaching his hotel in the city, RM revealed that his stay would be for four days and added that he would step out for dinner. As he sat at a roadside open-air restaurant, RM feasted on beer, burgers and fries. He said, "I'm starving right now. I'm out to grab some food. It's much quieter than I expected and feels like a rural town. I like the familiar atmosphere." RM attended Art Basel and explained on camera the details of the art fair. He also gave a glimpse as he had noodles and beer which was followed by soup noodles and wrap. Showing the pattern of a ping pong table, RM said, "The table looks like our (BTS) symbol." He also spoke about the art pieces as he viewed them. After that, RM took a tram to visit the Foundation Beyeler, a museum. He later took a walk through the city. On his third day, RM visited the Kunstmuseum Basel, the Vitra Design Museum and the gallery. As he walked around, RM showed a chair to his fans and said, "I have breaking news for you guys. Coldplay's Chris Martin made a chair and it's displayed in the Vitra Design Museum. If you see this Chris, give me a call. You're amazing." RM next visited Lucerne and hiked to Mount Rigi. Recalling his previous visit to Lucerne, RM added, "I remember the day of crossing that bridge and buying souvenirs." He was also reminded of Bon Voyage, a reality show featuring BTS members RM, Jin, Suga, J-Hope, Jimin, V and Jungkook. Speaking to the camera, RM said, "I rode the SSB train to Lucerne, rode a boat, rode the mountain train, walked down the track road, rode the cable cars, and now I'm on a boat planning to go ride the SSB again." RM's travel in Switzerland ended with a visit to the Museum Tinguely. Next, RM flew to Paris to attend the Pinault Collection and to visit Musee d'Orsay. He then went to Centre Georges-Pompidou and Orsay Museum. RM's vlog ended with him enjoying a Korean meal and then heading back to Seoul.

published_at : 2022-07-30T07:00:00Z

source : 2

topic : 13

In [5]:
news.drop(['published_at', 'source'], axis=1, inplace=True)

In [6]:
news.columns

Index(['title', 'content', 'topic'], dtype='object')

In [7]:
news['content'][0]

'After reaching his hotel in the city, RM revealed that his stay would be for four days and added that he would step out for dinner. As he sat at a roadside open-air restaurant, RM feasted on beer, burgers and fries. He said, "I\'m starving right now. I\'m out to grab some food. It\'s much quieter than I expected and feels like a rural town. I like the familiar atmosphere." RM attended Art Basel and explained on camera the details of the art fair. He also gave a glimpse as he had noodles and beer which was followed by soup noodles and wrap. Showing the pattern of a ping pong table, RM said, "The table looks like our (BTS) symbol." He also spoke about the art pieces as he viewed them. After that, RM took a tram to visit the Foundation Beyeler, a museum. He later took a walk through the city. On his third day, RM visited the Kunstmuseum Basel, the Vitra Design Museum and the gallery. As he walked around, RM showed a chair to his fans and said, "I have breaking news for you guys. Coldplay\'s Chris Martin made a chair and it\'s displayed in the Vitra Design Museum. If you see this Chris, give me a call. You\'re amazing." RM next visited Lucerne and hiked to Mount Rigi. Recalling his previous visit to Lucerne, RM added, "I remember the day of crossing that bridge and buying souvenirs." He was also reminded of Bon Voyage, a reality show featuring BTS members RM, Jin, Suga, J-Hope, Jimin, V and Jungkook. Speaking to the camera, RM said, "I rode the SSB train to Lucerne, rode a boat, rode the mountain train, walked down the track road, rode the cable cars, and now I\'m on a boat planning to go ride the SSB again." RM\'s travel in Switzerland ended with a visit to the Museum Tinguely. Next, RM flew to Paris to attend the Pinault Collection and to visit Musee d\'Orsay. He then went to Centre Georges-Pompidou and Orsay Museum. RM\'s vlog ended with him enjoying a Korean meal and then heading back to Seoul.'

Cleaning & Tokenizing

In [8]:
import string
import re
import nltk
punct_list = string.punctuation
stopwords_list = nltk.corpus.stopwords.words('english')
wl = nltk.WordNetLemmatizer()

In [9]:
def clean(text):
    # Remove_Punctuations
    removed_punct = "".join([char for char in text if char not in punct_list])
    # Create_Word_Tokens
    tokens = re.split('\W+', removed_punct)
    # Remove_Stop_Words
    without_stopword = [char for char in tokens if char not in stopwords_list]
    # Lemmatizing
    lemmatize_text = [wl.lemmatize(char)
                      for char in without_stopword]
    return lemmatize_text


news['Clean_Content'] = news['content'].apply(
    lambda x: clean(str(x).lower()))
news.head(2)

,title,content,topic,Clean_Content
0,"BTS: RM is reminded of Bon Voyage as he travels in Switzerland, gives glimpse of Chris Martin's ...","After reaching his hotel in the city, RM revealed that his stay would be for four days and added...",13,"[reaching, hotel, city, rm, revealed, stay, would, four, day, added, would, step, dinner, sat, r..."
1,RM recalls wondering if he 'made right decision by joining' BTS: I was thinking about how I woul...,RM aka Kim Namjoon was the first member to join BTS. The group released their debut single album...,13,"[rm, aka, kim, namjoon, first, member, join, bts, group, released, debut, single, album, 2, cool..."

In [10]:
news.columns

Index(['title', 'content', 'topic', 'Clean_Content'], dtype='object')

In [11]:
news.columns = ['Title', 'Original Content', 'Topic No.', 'Cleaned Content']
news.head()

,Title,Original Content,Topic No.,Cleaned Content
0,"BTS: RM is reminded of Bon Voyage as he travels in Switzerland, gives glimpse of Chris Martin's ...","After reaching his hotel in the city, RM revealed that his stay would be for four days and added...",13,"[reaching, hotel, city, rm, revealed, stay, would, four, day, added, would, step, dinner, sat, r..."
1,RM recalls wondering if he 'made right decision by joining' BTS: I was thinking about how I woul...,RM aka Kim Namjoon was the first member to join BTS. The group released their debut single album...,13,"[rm, aka, kim, namjoon, first, member, join, bts, group, released, debut, single, album, 2, cool..."
2,BTS: J-Hope and RM go bonkers at Billie Eilish's concert; ARMY rejoice seeing Namjoon and Hobi's...,"Billie Eilish's concert was held in Seoul, South Korea and it was attended by BTS' RM aka Kim Na...",7,"[billie, eilishs, concert, held, seoul, south, korea, attended, bts, rm, aka, kim, namjoon, jhop..."
3,"BTS: J-Hope proudly states he raised Jungkook, Jimin and Kim Taehyung; ARMY gets emotional [Watch]","BTS ARMY y'all would be missing the members a lot, right? Well, one of the BTS members Kim Seokj...",7,"[bts, army, yall, would, missing, member, lot, right, well, one, bts, member, kim, seokjin, aka,..."
4,BTS: Jin aka Kim Seokjin takes us through the Super Tuna journey; his unbridled excitement on ca...,BTS member Kim Seokjin aka Jin has the capacity to create diverse content. This has come through...,8,"[bts, member, kim, seokjin, aka, jin, capacity, create, diverse, content, come, brilliantly, pas..."

TF-IDF

In [12]:
from nltk import word_tokenize, sent_tokenize
from nltk.tokenize.treebank import TreebankWordDetokenizer

news['Sentence Token'] = news['Cleaned Content'].apply(
    lambda x: sent_tokenize("".join(TreebankWordDetokenizer().detokenize(x))))

In [13]:
news.head(2)

,Title,Original Content,Topic No.,Cleaned Content,Sentence Token
0,"BTS: RM is reminded of Bon Voyage as he travels in Switzerland, gives glimpse of Chris Martin's ...","After reaching his hotel in the city, RM revealed that his stay would be for four days and added...",13,"[reaching, hotel, city, rm, revealed, stay, would, four, day, added, would, step, dinner, sat, r...",[reaching hotel city rm revealed stay would four day added would step dinner sat roadside openai...
1,RM recalls wondering if he 'made right decision by joining' BTS: I was thinking about how I woul...,RM aka Kim Namjoon was the first member to join BTS. The group released their debut single album...,13,"[rm, aka, kim, namjoon, first, member, join, bts, group, released, debut, single, album, 2, cool...",[rm aka kim namjoon first member join bts group released debut single album 2 cool 4 skool june ...

In [14]:
def freq_matrix(sentences):
    frequency_matrix = {}

    for sent in sentences:
        freq_table = {}
        words = word_tokenize(sent)
        for word in words:
            if word in freq_table:
                freq_table[word] += 1
            else:
                freq_table[word] = 1

        frequency_matrix[sent[:15]] = freq_table

    return frequency_matrix


news['Frequency Matrix'] = news['Sentence Token'].apply(
    lambda x: freq_matrix(x))
news.head(1)
# news['freq_matrix'][0]

,Title,Original Content,Topic No.,Cleaned Content,Sentence Token,Frequency Matrix
0,"BTS: RM is reminded of Bon Voyage as he travels in Switzerland, gives glimpse of Chris Martin's ...","After reaching his hotel in the city, RM revealed that his stay would be for four days and added...",13,"[reaching, hotel, city, rm, revealed, stay, would, four, day, added, would, step, dinner, sat, r...",[reaching hotel city rm revealed stay would four day added would step dinner sat roadside openai...,"{'reaching hotel ': {'reaching': 1, 'hotel': 1, 'city': 2, 'rm': 12, 'revealed': 1, 'stay': 1, '..."

In [15]:

def tf_matrix(freq_matrix):
    tf_matrix = {}

    for sent, f_table in freq_matrix.items():
        tf_table = {}

        count_words_in_sentence = len(f_table)
        for word, count in f_table.items():
            tf_table[word] = count / count_words_in_sentence

        tf_matrix[sent] = tf_table

    return tf_matrix


news['TF Matrix'] = news['Frequency Matrix'].apply(lambda x: tf_matrix(x))
news.head(1)

,Title,Original Content,Topic No.,Cleaned Content,Sentence Token,Frequency Matrix,TF Matrix
0,"BTS: RM is reminded of Bon Voyage as he travels in Switzerland, gives glimpse of Chris Martin's ...","After reaching his hotel in the city, RM revealed that his stay would be for four days and added...",13,"[reaching, hotel, city, rm, revealed, stay, would, four, day, added, would, step, dinner, sat, r...",[reaching hotel city rm revealed stay would four day added would step dinner sat roadside openai...,"{'reaching hotel ': {'reaching': 1, 'hotel': 1, 'city': 2, 'rm': 12, 'revealed': 1, 'stay': 1, '...","{'reaching hotel ': {'reaching': 0.006535947712418301, 'hotel': 0.006535947712418301, 'city': 0...."

In [16]:
word_per_doc_table = {}
def docs_per_word_fn(freq_matrix):

    for sent, f_table in freq_matrix.items():
        for word, count in f_table.items():
            if word in word_per_doc_table:
                word_per_doc_table[word] += 1
            else:
                word_per_doc_table[word] = 1
    return word_per_doc_table
val=news['Frequency Matrix'].apply(lambda x: docs_per_word_fn(x))
count_docs_per_word=val.iloc[-1]
count_docs_per_word

{'reaching': 15,
 'hotel': 20,
 'city': 36,
 'rm': 388,
 'revealed': 153,
 'stay': 179,
 'would': 244,
 'four': 93,
 'day': 336,
 'added': 170,
 'step': 111,
 'dinner': 32,
 'sat': 28,
 'roadside': 2,
 'openair': 1,
 'restaurant': 20,
 'feasted': 2,
 'beer': 2,
 'burger': 1,
 'fry': 1,
 'said': 424,
 'im': 125,
 'starving': 2,
 'right': 190,
 'grab': 11,
 'food': 37,
 'much': 164,
 'quieter': 1,
 'expected': 58,
 'feel': 138,
 'like': 418,
 'rural': 1,
 'town': 21,
 'familiar': 6,
 'atmosphere': 14,
 'attended': 34,
 'art': 59,
 'basel': 5,
 'explained': 15,
 'camera': 68,
 'detail': 50,
 'fair': 5,
 'also': 690,
 'gave': 89,
 'glimpse': 52,
 'noodle': 19,
 'followed': 64,
 'soup': 13,
 'wrap': 7,
 'showing': 41,
 'pattern': 3,
 'ping': 1,
 'pong': 1,
 'table': 13,
 'look': 289,
 'bts': 715,
 'symbol': 3,
 'spoke': 71,
 'piece': 25,
 'viewed': 6,
 'took': 190,
 'tram': 1,
 'visit': 38,
 'foundation': 5,
 'beyeler': 1,
 'museum': 18,
 'later': 128,
 'walk': 18,
 'third': 69,
 'visited': 28,
 'kunstmuseum': 1,
 'vitra': 1,
 'design': 12,
 'gallery': 8,
 'walked': 24,
 'around': 156,
 'showed': 84,
 'chair': 12,
 'fan': 614,
 'breaking': 22,
 'news': 287,
 'guy': 67,
 'coldplays': 6,
 'chris': 19,
 'martin': 18,
 'made': 278,
 'displayed': 4,
 'see': 235,
 'give': 98,
 'call': 43,
 'youre': 28,
 'amazing': 72,
 'next': 140,
 'lucerne': 1,
 'hiked': 1,
 'mount': 2,
 'rigi': 2,
 'recalling': 6,
 'previous': 26,
 'remember': 35,
 'crossing': 2,
 'bridge': 4,
 'buying': 4,
 'souvenir': 1,
 'reminded': 14,
 'bon': 2,
 'voyage': 2,
 'reality': 21,
 'show': 287,
 'featuring': 64,
 'member': 652,
 'jin': 441,
 'suga': 359,
 'jhope': 405,
 'jimin': 388,
 'v': 381,
 'jungkook': 416,
 'speaking': 51,
 'rode': 2,
 'ssb': 1,
 'train': 10,
 'boat': 2,
 'mountain': 8,
 'track': 176,
 'road': 8,
 'cable': 1,
 'car': 26,
 'planning': 25,
 'go': 208,
 'ride': 16,
 'rms': 35,
 'travel': 28,
 'switzerland': 3,
 'ended': 62,
 'tinguely': 1,
 'flew': 9,
 'paris': 32,
 'attend': 29,
 'pinault': 1,
 'collection': 30,
 'musee': 1,
 'dorsay': 1,
 'went': 170,
 'centre': 29,
 'georgespompidou': 1,
 'orsay': 1,
 'vlog': 15,
 'enjoying': 43,
 'korean': 293,
 'meal': 26,
 'heading': 14,
 'back': 217,
 'seoul': 103,
 'aka': 248,
 'kim': 309,
 'namjoon': 98,
 'first': 384,
 'join': 127,
 'group': 390,
 'released': 276,
 'debut': 197,
 'single': 139,
 'album': 362,
 '2': 153,
 'cool': 44,
 '4': 77,
 'skool': 13,
 'june': 127,
 '12': 58,
 '2013': 52,
 'apart': 44,
 'feature': 85,
 'interview': 71,
 'hypebeast': 2,
 'difficult': 27,
 'question': 47,
 'answer': 30,
 'truthfully': 1,
 'recently': 202,
 'watched': 30,
 'everything': 68,
 'everywhere': 15,
 'film': 55,
 'visualized': 1,
 'many': 211,
 'idea': 43,
 'multiple': 45,
 'version': 48,
 'existing': 6,
 'based': 35,
 'small': 34,
 'choice': 24,
 'often': 45,
 'think': 164,
 'continued': 60,
 'study': 8,
 'became': 85,
 'something': 104,
 'musician': 33,
 'honest': 19,
 'one': 524,
 'decision': 48,
 'thought': 98,
 'become': 95,
 'part': 203,
 'boy': 260,
 'band': 181,
 'late': 40,
 '2000s': 3,
 'zico': 4,
 'changmo': 2,
 'giriboy': 2,
 'people': 191,
 'started': 136,
 'journey': 39,
 'drifted': 2,
 'away': 80,
 'world': 287,
 'tormented': 2,
 'liked': 28,
 'enjoyed': 29,
 'music': 417,
 'love': 317,
 'wondered': 14,
 'whether': 48,
 'joining': 30,
 'time': 435,
 'treated': 17,
 'complete': 46,
 'outsider': 5,
 'hiphop': 35,
 'community': 97,
 'stressed': 6,
 'constantly': 20,
 'thinking': 33,
 'able': 65,
 'overcome': 5,
 'perception': 3,
 'define': 1,
 'solo': 262,
 'mixtape': 33,
 '2015': 33,
 'three': 124,
 'year': 366,
 'second': 151,
 'mono': 12,
 'collaborated': 37,
 'artist': 217,
 'wale': 5,
 'younha': 6,
 'warren': 6,
 'g': 15,
 'gaeko': 5,
 'krizz': 5,
 'kaliko': 5,
 'mfbty': 5,
 'fall': 28,
 'primary': 7,
 'lil': 10,
 'na': 67,
 'x': 55,
 'erykah': 11,
 'badu': 11,
 'anderson': 16,
 'paak': 15,
 'earlier': 136,
 'month': 152,
 'fulllength': 20,
 'indigo': 35,
 'billie': 7,
 'eilishs': 3,
 'concert': 232,
 'held': 97,
 'south': 222,
 'korea': 197,
 'jung': 109,
 'hoseok': 67,
 'picture': 190,
 'video': 388,
 'hobi': 64,
 'attending': 25,
 'going': 195,
 'viral': 85,
 'social': 140,
 'medium': 169,
 'gala': 4,
 'billy': 2,
 'really': 145,
 'audience': 61,
 'grooved': 13,
 'army': 472,
 'rejoicing': 2,
 'fact': 89,
 'got': 190,
 'eilish': 6,
 'tour': 73,
 'current': 18,
 'stop': 52,
 'performed': 98,
 'full': 114,
 'vigour': 1,
 'enthusiasm': 7,
 'packed': 11,
 'seems': 119,
 'seen': 206,
 'sitting': 28,
 'amongst': 22,
 'favourite': 132,
 'jam': 3,
 'seat': 15,
 'nobody': 8,
 'honestly': 15,
 'best': 171,
 'content': 76,
 'long': 128,
 'heart': 131,
 'posted': 88,
 'instagram': 255,
 'picked': 19,
 'shared': 280,
 'online': 83,
 'widely': 9,
 'discussed': 23,
 'hollywood': 81,
 'leader': 133,
 'quite': 89,
 'active': 42,
 'handle': 72,
 'couple': 92,
 'memento': 2,
 'posing': 26,
 'singersongwriter': 19,
 'brother': 40,
 'finneas': 2,
 'baird': 1,
 'oconnell': 1,
 'two': 227,
 'performing': 67,
 'consists': 49,
 'hand': 98,
 'wrist': 6,
 'entry': 20,
 'captioned': 38,
 'post': 166,
 'saying': 148,
 'bad': 44,
 'well': 340,
 'flip': 3,
 'side': 93,
 'watching': 41,
 'perform': 87,
 'equally': 8,
 'heartwarming': 17,
 'check': 89,
 'tweet': 87,
 'work': 154,
 'front': 81,
 'busy': 43,
 'promoting': 14,
 'jack': 56,
 'box': 65,
 'yet': 146,
 'reveal': 19,
 'deets': 4,
 'project': 103,
 'happens': 16,
 'birthday': 70,
 'maybe': 25,
 'hed': 2,
 'announce': 15,
 'coming': 91,
 'run': 114,
 'tonight': 12,
 'yall': 25,
 'missing': 28,
 'lot': 198,
 'seokjin': 94,
 'enlisted': 21,
 'military': 131,
 'others': 110,
 'six': 46,
 'enlist': 39,
 'till': 30,
 'could': 122,
 'calm': 25,
 'newest': 5,
 'bangtan': 143,
 'bomb': 27,
 'jhopes': 49,
 'japan': 23,
 'week': 129,
 'ago': 90,
 'mama': 27,
 'award': 129,
 'latest': 200,
 'several': 117,
 'exhibition': 5,
 'tokyo': 5,
 'dressed': 54,
 'casuals': 3,
 'section': 41,
 'concept': 56,
 'photo': 162,
 'proof': 94,
 'say': 131,
 'never': 78,
 'listens': 2,
 'grown': 13,
 'handsome': 62,
 'boast': 10,
 'raising': 10,
 'taehyung': 175,
 'face': 103,
 'maknae': 55,
 'line': 72,
 'super': 63,
 'adorable': 50,
 'seeing': 57,
 'whole': 84,
 'reminisce': 4,
 'memory': 30,
 'even': 237,
 'dance': 159,
 'old': 86,
 'choreography': 39,
 'left': 145,
 'emotional': 53,
 'behaviour': 6,
 'meanwhile': 133,
 'popularity': 58,
 'reached': 33,
 'higher': 8,
 'success': 38,
 'drop': 51,
 'sunshine': 9,
 'capacity': 3,
 'create': 22,
 'diverse': 7,
 'come': 268,
 'brilliantly': 1,
 'past': 64,
 'making': 159,
 'traditional': 20,
 'alcohol': 14,
 'chef': 14,
 'baek': 10,
 'dong': 13,
 'entertaining': 7,
 'youngji': 2,
 'multitalented': 2,
 'saw': 70,
 'sea': 12,
 'today': 148,
 'tv': 64,
 'jins': 63,
 'fishing': 5,
 'trip': 31,
 'bumzu': 1,
 'producer': 76,
 'big': 170,
 'hit': 171,
 'seventeen': 35,
 'vocalist': 49,
 'overall': 13,
 'grey': 19,
 'shirt': 39,
 'life': 152,
 'jacket': 39,
 'know': 310,
 'fond': 7,
 'caught': 21,
 'fish': 3,
 'indeed': 39,
 'bluefin': 1,
 'tuna': 9,
 'take': 227,
 'bait': 1,
 'common': 5,
 'water': 20,
 'find': 58,
 'near': 24,
 'jeju': 14,
 'island': 20,
 'happiness': 20,
 'catching': 4,
 'boundless': 1,
 'head': 54,
 'soon': 186,
 'turn': 48,
 '31': 27,
 'worried': 28,
 'freezing': 3,
 'winter': 25,
 'getting': 100,
 'home': 82,
 'qatar': 29,
 'chicago': 26,
 'final': 26,
 'lollapalooza': 41,
 'festival': 50,
 'happen': 21,
 'july': 54,
 '2o22': 2,
 'live': 219,
 'new': 351,
 'weverse': 117,
 'word': 84,
 'crazy': 46,
 'hair': 55,
 'collar': 13,
 'bone': 1,
 'flawless': 4,
 'skin': 16,
 'eating': 15,
 'dropped': 106,
 'five': 37,
 'kg': 5,
 'lead': 52,
 'dancer': 49,
 'rapper': 113,
 'sub': 6,
 'performer': 21,
 'preparing': 34,
 'hard': 103,
 'looked': 66,
 'great': 83,
 'moment': 121,
 'grunting': 1,
 'voice': 70,
 'vlive': 20,
 'kind': 73,
 'noise': 10,
 'hear': 31,
 'workout': 9,
 'discussing': 16,
 'thirst': 14,
 'trap': 12,
 'innocuous': 1,
 'manner': 17,
 'exploring': 7,
 'option': 7,
 'thing': 145,
 'banging': 2,
 'song': 410,
 'rock': 33,
 'vibe': 56,
 'arson': 18,
 'good': 163,
 'critical': 6,
 'reception': 1,
 'spotify': 44,
 'desert': 7,
 'area': 18,
 'blue': 72,
 'outfit': 56,
 'white': 73,
 'clip': 104,
 'comprised': 6,
 'mirror': 12,
 'selfies': 28,
 'holding': 36,
 'included': 52,
 'outro': 5,
 'ego': 10,
 'essentially': 7,
 'interpreted': 5,
 'lyric': 68,
 'complex': 13,
 'feeling': 67,
 'pressure': 12,
 'reshape': 2,
 'different': 122,
 'interpretation': 1,
 'wear': 27,
 'mask': 21,
 'hide': 5,
 'dont': 86,
 'particularly': 11,
 'want': 139,
 'sometimes': 18,
 'hid': 3,
 'didnt': 55,
 'either': 20,
 'came': 155,
 'accept': 12,
 'identity': 12,
 'reacting': 83,
 'yes': 36,
 'hobiyesterday': 1,
 'tomorrow': 42,
 'forever': 30,
 'way': 138,
 'appreciates': 2,
 'proofofjhope': 1,
 'beloved': 27,
 'tweeted': 99,
 'person': 159,
 'precious': 31,
 'powerful': 26,
 'beautiful': 75,
 'acceptance': 7,
 'unconditional': 3,
 'bond': 21,
 'aaah': 1,
 'babe': 2,
 'teary': 2,
 'eye': 78,
 'btsproof': 3,
 'intimate': 3,
 'wrote': 215,
 'another': 276,
 'read': 377,
 'hiding': 4,
 'aspect': 6,
 'embracing': 3,
 'growth': 10,
 'realising': 1,
 'every': 129,
 'downside': 1,
 'inspired': 19,
 'better': 54,
 'persona': 27,
 'thank': 83,
 'sharing': 103,
 'u': 293,
 'finding': 13,
 'always': 157,
 'cute': 56,
 'hope': 102,
 'freedom': 3,
 'relationship': 27,
 'boundary': 4,
 'glad': 17,
 'proud': 48,
 'choosing': 4,
 'btss': 14,
 'release': 209,
 '10': 155,
 'consist': 10,
 'songsyet': 7,
 'born': 72,
 'singer': 210,
 'fake': 33,
 'need': 80,
 'jamais': 16,
 'vu': 16,
 'seesaw': 18,
 'moon': 39,
 'fire': 43,
 'luv': 32,
 'danger': 18,
 'idol': 100,
 'dynamite': 53,
 'butter': 83,
 'famous': 43,
 'little': 92,
 'make': 223,
 'headline': 34,
 'known': 166,
 'inquisitive': 1,
 'here': 21,
 'scoop': 2,
 'puzzled': 1,
 'frequent': 1,
 'outing': 9,
 'model': 21,
 'irene': 6,
 'wondering': 23,
 'brewing': 3,
 'currently': 115,
 'york': 16,
 'chilling': 5,
 'friend': 101,
 'gone': 51,
 'racking': 1,
 'connection': 11,
 'spotted': 26,
 'standing': 23,
 'alongside': 54,
 'cheered': 16,
 'listening': 40,
 'party': 32,
 'allkpop': 7,
 'reported': 45,
 'user': 83,
 'called': 122,
 'exactly': 17,
 'forum': 9,
 'however': 155,
 'netizens': 11,
 'claiming': 7,
 'already': 89,
 'boyfriend': 21,
 'responded': 34,
 'netizen': 2,
 'follows': 19,
 'shes': 6,
 'celebrity': 35,
 'questioned': 11,
 'following': 107,
 'girlfriend': 5,
 'okay': 37,
 'jungkooks': 66,
 '25th': 7,
 'golden': 68,
 'jeon': 50,
 'biggest': 125,
 'trend': 40,
 'across': 95,
 'globe': 56,
 'pouring': 8,
 'wish': 66,
 'twitter': 283,
 'portal': 12,
 'september': 53,
 'husband': 7,
 'trending': 49,
 'due': 71,
 'hyung': 54,
 'wished': 23,
 'weversetwitter': 1,
 'firstly': 7,
 'happy': 116,
 'bruhhh': 2,
 'everrrr': 2,
 'jk': 42,
 'house': 46,
 'hybe': 58,
 'blazer': 11,
 'secondly': 3,
 'tipsy': 3,
 'grooving': 9,
 'groovyyyy': 2,
 'hashtag': 17,
 'racing': 3,
 'claim': 9,
 'per': 84,
 'daily': 19,
 'monthly': 4,
 'wherein': 20,
 'character': 40,
 'goofed': 7,
 'talking': 102,
 'phrase': 7,
 'announcement': 60,
 'hiatus': 52,
 'charlie': 29,
 'puth': 22,
 'snoop': 20,
 'dogg': 13,
 'benny': 16,
 'blanco': 15,
 'along': 140,
 'missed': 24,
 'last': 237,
 'night': 74,
 'let': 181,
 'delighted': 9,
 'mark': 41,
 'beginning': 28,
 'holiday': 12,
 'season': 25,
 'occasion': 27,
 'chuseok': 3,
 'hanbok': 2,
 'worn': 7,
 'hangawi': 1,
 'major': 30,
 'midautumn': 1,
 'harvest': 2,
 'threeday': 1,
 'celebrated': 33,
 '15th': 16,
 '8th': 15,
 'lunar': 2,
 'calendar': 2,
 'began': 53,
 '9': 68,
 'family': 46,
 'gather': 5,
 'enjoy': 42,
 'together': 176,
 'ancestor': 1,
 'plentiful': 2,
 'official': 135,
 'page': 36,
 'seven': 83,
 'reel': 4,
 'celebrate': 24,
 'sensual': 3,
 'charm': 36,
 'piercing': 4,
 'gaze': 6,
 'amid': 13,
 'backdrop': 9,
 'moonlight': 1,
 'popular': 125,
 'dalmajung': 2,
 'merch': 10,
 'immensely': 17,
 'anticipated': 11,
 'featured': 57,
 'including': 123,
 'pandora': 8,
 'created': 42,
 'history': 65,
 'performance': 188,
 'septet': 45,
 'era': 10,
 'hobis': 12,
 'scary': 5,
 'yep': 4,
 'usually': 25,
 'considered': 18,
 'cheerful': 4,
 'loses': 2,
 'he': 58,
 'scariest': 2,
 'eldest': 53,
 'hearty': 1,
 'laugh': 34,
 'whereas': 7,
 'serious': 12,
 'kinda': 11,
 'furious': 4,
 'reason': 59,
 'goofing': 7,
 'stephen': 4,
 'colbert': 2,
 'messed': 4,
 'towards': 60,
 'end': 127,
 'checking': 6,
 'tape': 2,
 'utter': 2,
 'anybody': 2,
 'goof': 3,
 'immediately': 19,
 'catch': 8,
 'redo': 1,
 '3js': 2,
 'megan': 10,
 'thee': 8,
 'stallion': 9,
 'remix': 21,
 'practised': 9,
 'shot': 39,
 'whenever': 25,
 'naturally': 12,
 'looking': 89,
 'get': 250,
 'telepathically': 2,
 'funny': 41,
 'admirable': 3,
 'excited': 79,
 'gift': 38,
 'mandatory': 48,
 'service': 71,
 'titled': 54,
 'astronaut': 47,
 'freaked': 1,
 'link': 4,
 'reference': 15,
 'special': 125,
 'mr': 14,
 'worldwide': 52,
 'handsom': 1,
 'amidst': 6,
 'excitement': 22,
 'wootteo': 5,
 'huge': 78,
 'confusion': 7,
 'mystery': 3,
 'solve': 2,
 'logo': 8,
 'teaser': 70,
 'seokjins': 7,
 'broke': 25,
 'berserk': 7,
 'promotional': 14,
 'account': 86,
 'image': 42,
 'resembled': 1,
 'theme': 31,
 'everyone': 114,
 'especially': 37,
 'promotion': 27,
 'minute': 48,
 'comment': 182,
 'wootteos': 1,
 'commented': 95,
 'tell': 53,
 'anything': 45,
 'surprised': 32,
 'asked': 164,
 'given': 72,
 'mission': 7,
 'company': 54,
 'releasing': 34,
 '28th': 8,
 'october': 104,
 'cancelled': 5,
 'request': 21,
 'delay': 7,
 'enlistment': 46,
 'begin': 43,
 'procedure': 5,
 'hook': 8,
 'enhypen': 17,
 'txt': 28,
 'jean': 13,
 'among': 110,
 'challenge': 21,
 'dancing': 61,
 'though': 82,
 'caption': 28,
 'folded': 5,
 'purple': 35,
 'emojis': 24,
 'translated': 43,
 'btsinthemoment': 1,
 'include': 44,
 'jyahope': 1,
 'mine': 10,
 'hm': 1,
 'teased': 36,
 'jungkookies': 2,
 'compilation': 4,
 'elder': 16,
 'praise': 23,
 'joon': 20,
 'ta': 3,
 'story': 111,
 'ok': 14,
 'baby': 40,
 'separately': 6,
 'still': 97,
 'fifa': 32,
 'cup': 36,
 'brief': 22,
 'chose': 28,
 'introduce': 3,
 'danced': 24,
 'slower': 2,
 'inside': 48,
 'room': 107,
 'wednesday': 24,
 'stayed': 20,
 'emerged': 15,
 'staff': 26,
 'conversation': 35,
 'dreamer': 14,
 'opening': 33,
 'ceremony': 56,
 'joined': 63,
 'qatari': 5,
 'fahad': 7,
 'alkubaisi': 1,
 'boybands': 3,
 'talkedabout': 1,
 'throwback': 8,
 'without': 62,
 'share': 103,
 'struggle': 12,
 'debuted': 86,
 'predebut': 9,
 'background': 35,
 'worked': 68,
 '2am': 1,
 'jo': 5,
 'kwan': 1,
 'performancevideo': 1,
 'kwans': 1,
 'da': 11,
 'extra': 12,
 'mv': 50,
 'tremendous': 6,
 'ruling': 13,
 'industry': 63,
 'altogether': 3,
 'trainee': 15,
 'animal': 7,
 'stage': 160,
 'interestingly': 9,
 'met': 49,
 'talk': 79,
 'buzzing': 7,
 'hot': 82,
 'gifted': 5,
 'hence': 18,
 'brought': 45,
 'songsvideos': 1,
 'schedule': 66,
 'cooking': 9,
 'storm': 6,
 'butterfly': 9,
 'honoured': 10,
 'platinum': 8,
 'daesangs': 2,
 '2019': 63,
 ...}

In [17]:
import math
def idf_matrix_fn(freq_matrix, count_doc_per_word, total_documents):
    idf_matrix_temp = {}

    for sent, f_table in freq_matrix.items():
        idf_table = {}

        for word in f_table.keys():
            idf_table[word] = math.log10(total_documents / float(count_doc_per_word[word]))

        idf_matrix_temp[sent] = idf_table

    return idf_matrix_temp
news['Idf Matrix']=news['Frequency Matrix'].apply(lambda x:idf_matrix_fn(x,count_docs_per_word,810))
# idf_matrix
news.head()

,Title,Original Content,Topic No.,Cleaned Content,Sentence Token,Frequency Matrix,TF Matrix,Idf Matrix
0,"BTS: RM is reminded of Bon Voyage as he travels in Switzerland, gives glimpse of Chris Martin's ...","After reaching his hotel in the city, RM revealed that his stay would be for four days and added...",13,"[reaching, hotel, city, rm, revealed, stay, would, four, day, added, would, step, dinner, sat, r...",[reaching hotel city rm revealed stay would four day added would step dinner sat roadside openai...,"{'reaching hotel ': {'reaching': 1, 'hotel': 1, 'city': 2, 'rm': 12, 'revealed': 1, 'stay': 1, '...","{'reaching hotel ': {'reaching': 0.006535947712418301, 'hotel': 0.006535947712418301, 'city': 0....","{'reaching hotel ': {'reaching': 1.7323937598229686, 'hotel': 1.6074550232146685, 'city': 1.3521..."
1,RM recalls wondering if he 'made right decision by joining' BTS: I was thinking about how I woul...,RM aka Kim Namjoon was the first member to join BTS. The group released their debut single album...,13,"[rm, aka, kim, namjoon, first, member, join, bts, group, released, debut, single, album, 2, cool...",[rm aka kim namjoon first member join bts group released debut single album 2 cool 4 skool june ...,"{'rm aka kim namj': {'rm': 6, 'aka': 1, 'kim': 1, 'namjoon': 1, 'first': 3, 'member': 1, 'join':...","{'rm aka kim namj': {'rm': 0.04477611940298507, 'aka': 0.007462686567164179, 'kim': 0.0074626865...","{'rm aka kim namj': {'rm': 0.31965329328444253, 'aka': 0.5140333380524335, 'kim': 0.418526539453..."
2,BTS: J-Hope and RM go bonkers at Billie Eilish's concert; ARMY rejoice seeing Namjoon and Hobi's...,"Billie Eilish's concert was held in Seoul, South Korea and it was attended by BTS' RM aka Kim Na...",7,"[billie, eilishs, concert, held, seoul, south, korea, attended, bts, rm, aka, kim, namjoon, jhop...",[billie eilishs concert held seoul south korea attended bts rm aka kim namjoon jhope aka jung ho...,"{'billie eilishs ': {'billie': 11, 'eilishs': 6, 'concert': 10, 'held': 1, 'seoul': 4, 'south': ...","{'billie eilishs ': {'billie': 0.0763888888888889, 'eilishs': 0.041666666666666664, 'concert': 0...","{'billie eilishs ': {'billie': 2.063386978864393, 'eilishs': 2.4313637641589874, 'concert': 0.54..."
3,"BTS: J-Hope proudly states he raised Jungkook, Jimin and Kim Taehyung; ARMY gets emotional [Watch]","BTS ARMY y'all would be missing the members a lot, right? Well, one of the BTS members Kim Seokj...",7,"[bts, army, yall, would, missing, member, lot, right, well, one, bts, member, kim, seokjin, aka,...",[bts army yall would missing member lot right well one bts member kim seokjin aka jin enlisted m...,"{'bts army yall w': {'bts': 3, 'army': 1, 'yall': 1, 'would': 1, 'missing': 1, 'member': 4, 'lot...","{'bts army yall w': {'bts': 0.02702702702702703, 'army': 0.009009009009009009, 'yall': 0.0090090...","{'bts army yall w': {'bts': 0.054178977077569156, 'army': 0.234543020244562, 'yall': 1.510545010..."
4,BTS: Jin aka Kim Seokjin takes us through the Super Tuna journey; his unbridled excitement on ca...,BTS member Kim Seokjin aka Jin has the capacity to create diverse content. This has come through...,8,"[bts, member, kim, seokjin, aka, jin, capacity, create, diverse, content, come, brilliantly, pas...",[bts member kim seokjin aka jin capacity create diverse content come brilliantly past day making...,"{'bts member kim ': {'bts': 4, 'member': 3, 'kim': 3, 'seokjin': 3, 'aka': 3, 'jin': 5, 'capacit...","{'bts member kim ': {'bts': 0.0425531914893617, 'member': 0.031914893617021274, 'kim': 0.0319148...","{'bts member kim ': {'bts': 0.054178977077569156, 'member': 0.09423742314672953, 'kim': 0.418526..."

In [18]:

def tf_idf_matrix_fn(tf_matrix, idf_matrix):
    tf_idf_matrix = {}

    for (sent1, f_table1), (sent2, f_table2) in zip(tf_matrix.items(), idf_matrix.items()):

        tf_idf_table = {}

        for (word1, value1), (word2, value2) in zip(f_table1.items(),
                                                    f_table2.items()):  # here, keys are the same in both the table
            tf_idf_table[word1] = float(value1 * value2)

        tf_idf_matrix[sent1] = tf_idf_table

    return tf_idf_matrix